---
title: "Regression_Methods2(Question 3)"
author: "Oluwanifemi"
date: "2024-09-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(stats)
library(alr4)
```



```{r}
file <- wblake
View(file)

data(wblake)

```

## Question 3(a)



```{r}
## 66.67 or 67 % of the sample size
smp_size <- floor((2/3) * nrow(wblake))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(wblake)), size = smp_size)
train_ind1 <- sample(x= 1:nrow(wblake), smp_size)

train <- wblake[train_ind, ]
test <- wblake[-train_ind, ]

train1 <- wblake[train_ind1, ]
test1 <- wblake[-train_ind1, ]


```


## Question 3(b)

```{r}
lage <- lm(Length ~ Age, data = train1)
summary(lage)

observed <- train1$Length

predicted <- lage$fitted.values

#sse1 <- sum(residuals^2)
#sse1

sst2 <- sum((observed-mean(observed))^2)
sst2


sse2 <- sum((observed - predicted)^2)
sse2

r2 <- 1-(sse2/sst2)
r2



```

## Question 3(c)

```{r}
mse2<-mean(lage$residuals^2)
mse2

predicted_values <- predict(lage, newdata = test1)

# Step 4: Calculate the MSE on the test data
actual_values <- test1$Length
mse_test <- mean((actual_values - predicted_values)^2)
mse_test

```



## Question 3(d)

```{r}
#Trying different models to get a better one
train1$Age_Squared <-c((train$Age)^2)
test1$Age_Squared <-c((test$Age)^2)

model <- lm(Length~Age_Squared, data = train1)
summary(model)

predicted_values1 <- predict(model, newdata = test1)

# Step 4: Calculate the MSE on the test data
actual_values1 <- test1$Length
mse_test1 <- mean((actual_values1 - predicted_values1)^2)
mse_test1

model_1 <- lm(Scale~Age_Squared,data = train1)
summary(model_1)
predicted_values2 <- predict(model_1, newdata = test1)

# Step 4: Calculate the MSE on the test data
actual_values2 <- test1$Length
mse_test2 <- mean((actual_values2 - predicted_values2)^2)
mse_test2

model_2 <- lm(Length~Age_Squared+Scale, data = train1)
summary(model_2)

predicted_values3 <- predict(model_2, newdata = test1)

# Step 4: Calculate the MSE on the test data
actual_values3 <- test1$Length
mse_test3 <- mean((actual_values3 - predicted_values3)^2)
mse_test3

model_3 <- lm(Scale~Age_Squared + Length,data = train1)
summary(model_3)

predicted_values4 <- predict(model_3, newdata = test1)

# Step 4: Calculate the MSE on the test data
actual_values4 <- test1$Length
mse_test4 <- mean((actual_values4 - predicted_values4)^2)
mse_test

```
#### The best model with a lower mse is the model (quadratic) where Length is y and Age_squared is x + another variable Scale. the initial mse is 917.07 but the one for this new model is 487.00. 